### ISSUE TITLE
Help running script option 4 please

### ISSUE THREAD

**Issue by icescoop12** [neothematrix/noip-renew#59]
hi
running on bookwork debian raspbian
ran bash setup.sh, and set up account info
im stuck on the last bit,(after installing script and entering username and password(also didn't get option 3 about the crontab))
`4.Run noip-renew-USERNAME command.`
tried as user and root and with sudo commands to run above but i get:
`theskid@raspberrypi:~$ cd /usr/local/bin theskid@raspberrypi:/usr/local/bin $ bash noip-renew-theskid.sh noip-renew-theskid.sh: line 10: ./noip-renew.py: Permission denied 
theskid@raspberrypi:/usr/local/bin $ sudo bash noip-renew-theskid.sh noip-renew-theskid.sh: line 10: ./noip-renew.py: Permission denied 
theskid@raspberrypi:/usr/local/bin $ su Password:  
root@raspberrypi:/usr/local/bin# bash noip-renew-theskid.sh noip-renew-theskid.sh: line 10: ./noip-renew.py: Permission denied 
root@raspberrypi:/usr/local/bin# `

**Comment by neothematrix** [comment]
try with: `chmod +x noip-renew.py` first, then re-run `bash noip-renew-theskid.sh`

**Comment by icescoop12** [comment]
thanks but now i get this:
`Traceback (most recent call last):
  File "/home/theskid/.local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theskid/.local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 89, in driver_location
    args = [str(self.get_binary()), "--browser", browser]
                ^^^^^^^^^^^^^^^^^
  File "/home/theskid/.local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 63, in get_binary
    raise WebDriverException(f"Unsupported platform/architecture combination: {sys.platform}/{arch}")
selenium.common.exceptions.WebDriverException: Message: Unsupported platform/architecture combination: linux/aarch64


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/./noip-renew.py", line 234, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/bin/./noip-renew.py", line 215, in main
    return (Robot(noip_username, noip_password, debug)).run()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/./noip-renew.py", line 52, in __init__
    self.browser = self.init_browser()
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/./noip-renew.py", line 67, in init_browser
    browser = webdriver.Chrome(options=options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theskid/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/theskid/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 49, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theskid/.local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
`

**Comment by icescoop12** [comment]
chromedriver is in path:

`theskid@raspberrypi:/usr/local/bin` $ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games`

its in  here: /usr/bin

**Comment by neothematrix** [comment]
mmm are you sure the setup.sh didn't throw any error and all components were installed properly? you can re-run it if you want and paste here the output.

**Comment by neothematrix** [comment]
ciao @icescoop12 hopefully you've solved your issue, if not, please feel free to reopen!
